<?php require_once __DIR__. "/autoload/autoload.php"; ?><?php require_once __DIR__. "/layout/header.php"; ?>
<div class="col-md-9" id="tintuc">
	<section class="box-main1">
		<h3 class="title-main"><a href="">Quy định bảo hành </a> </h3>
		<p>&nbsp;</p>
		<div class="content">
			<h1 style="color: rgb(0, 51, 120); margin-top: 0px; margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-family: Tahoma, Arial; text-align: center;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">QUY ĐỊNH BẢO HÀNH</strong></h1>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">&nbsp;</strong></p>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">&nbsp;</strong><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">1.&nbsp;&nbsp;</strong><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">ĐIỀU KIỆN BẢO HÀNH:</strong></p>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;"><br></strong></p>
			<ul style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px 0px 0px 50px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;">
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Đối với các thiết bị được cấp phiếu bảo hành, phải xuất trình Phiếu bảo hành và có tem bảo hành của Storm Store còn trong thời hạn bảo hành.</li>
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Tem bảo hành, mã vạch số serial, emei của sản phẩm phải còn nguyên vẹn, không có dấu hiệu cạo sửa, tẩy xóa, bị rách, mờ.</li>
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Những hư hỏng của thiết bị được xác định do lỗi kỹ thuật hoặc lỗi của nhà sản xuất.</li>
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Màn hình LCD có số điểm chấm từ 05 điểm trở lên.</li>
			</ul>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">&nbsp;</strong></p>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">2. KHÔNG BẢO HÀNH ĐỐI VỚI:</strong></p>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;"><br></strong></p>
			<ul style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px 0px 0px 50px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;">
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Thiết bị có dấu hiệu dung dịch lạ, có nước vào, có vết ẩm ướt, bị đứt mạch, bị trầy xước, bể mẻ, móp méo, biến dạng, có dấu hiệu cháy nổ, nám, phù tụ, gỉ sét, chuột bọ, côn trùng xâm nhập, ...</li>
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Thiết bị hư hỏng do thiên tai, hỏa hoạn, sử dụng nguồn điện không ổn định hoặc do lắp đặt, vận chuyển không đúng quy cách, …</li>
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Màn hình LCD bị loang ố màu.</li>
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Dữ liệu trong các thiết bị lưu trữ, Bản quyền phần mềm</li>
				<li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Các phụ kiện kèm theo thiết bị như: bao lụa, đầu phun mực của máy in, bộ dây sạc, tai nghe, cable nối, vỏ máy, nút công tắc, dây điện, remote điều khiển, quạt tản nhiệt, sản phẩm tặng kèm theo chương trình khuyến mãi.</li>
			</ul>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px; text-align: center;">&nbsp;</p>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px; text-align: center;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">RẤT HÂN HẠNH ĐƯỢC PHỤC VỤ QUÝ KHÁCH</strong></span></p>
		</div>
	</section>
</div>
<?php require_once __DIR__. "/layout/footer.php"; ?>    