<?php require_once __DIR__. "/autoload/autoload.php"; ?>
<?php require_once __DIR__. "/layout/header.php"; ?>
<div class="col-md-9">
	<section class="box-main1">
		<h3 class="title-main"><a href="">Quy định đổi hàng</a> </h3>
		&nbsp;
		<div class="content">
			<h3 style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px; color: rgb(51, 51, 51); line-height: normal;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;">Linh kiện đổi hàng phải đáp ứng các điều kiện sau:</span></h3>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;">&nbsp;</p>
			<ul class="arrow" style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px 0px 0px 50px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;"><span class="icon" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline;">&nbsp;</span>Còn nguyên vẹn, đầy đủ như lúc ban đầu giao cho Quý khách (bao bì và những phụ kiện kèm theo).</span></li><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;"><span class="icon" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline;">&nbsp;</span>Bị lỗi kỹ thuật hoặc không tương thích.</span></li><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;"><span class="icon" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline;">&nbsp;</span>Không quá 5 ngày và còn giữ phiếu mua hàng (phiếu xuất kho hoặc hóa đơn tài chính).</span></li></ul>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;">&nbsp;</p>
			<h3 style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px; color: rgb(51, 51, 51); line-height: normal;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;">Không đổi lại với những thiết bị sau:</span></h3>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;">&nbsp;</p>
			<ul class="arrow" style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px 0px 0px 50px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""></li><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;"><span class="icon" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline;">&nbsp;</span>Thiết bị biến dạng, trầy xước hoặc va chạm.</span></li><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;">Thiết bị có dấu hiệu cháy nổ.</span></li><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;">Quà tặng.</span></li></ul>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;">&nbsp;</p>
			<h3 style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px; color: rgb(51, 51, 51); line-height: normal;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;">Giờ đổi hàng:</span></h3>
			<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;">&nbsp;</p>
			<ul class="arrow" style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px 0px 0px 50px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;">Sáng 9g30 – 11g30</span></li><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;">Chiều: 14g30 – 16g30</span></li><li style="margin: 0px; padding: 0px 0px 0px 30px; border: 0px; outline: 0px; vertical-align: baseline; background: url(" http:="" vitinhphongvu.com.vn="" templates="" ja_zeolite_ii="" images="" bullet.gif")="" 20px="" 8px="" no-repeat="" transparent;"=""><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: 10pt;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; color: red;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; text-decoration-line: underline;">CHỦ NHẬT KHÔNG ĐỔI HÀNG</span></span></strong></span></li></ul>
			<div style="font-size: 1.5em;">
			</div>
		</section>
	</div>
<?php require_once __DIR__. "/layout/footer.php"; ?>    