<?php require_once __DIR__. "/autoload/autoload.php"; ?>
<?php require_once __DIR__. "/layout/header.php"; ?>
<div class="col-md-9 ">
	<section class="box-main1">
		<h3 class="title-main"><a href="">Thanh toán và giao hàng</a> </h3>
		&nbsp;
		<h3 style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px; color: rgb(51, 51, 51); line-height: normal;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: medium;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">I/ PHƯƠNG THỨC THANH TOÁN</strong></span></h3>
		<div id="vmMainPage" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(205, 216, 246); font-family: Arial, Helvetica, sans-serif; font-size: 12px;">
			<table class="vmbasket" border="0" cellspacing="0" cellpadding="2" width="100%" style="margin: 10px 0px 0px; padding: 0px; border: 1px solid rgb(223, 235, 247); outline: 0px; vertical-align: baseline; cursor: default;">
				<tbody style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline;">
					<tr class="sectiontableheader" style="padding: 5px; color: rgb(51, 51, 51);">
						<td width="200" align="center" style="margin: 8px; padding: 5px; color: rgb(0, 0, 0); font-weight: bold; cursor: text; background-image: none; background-attachment: scroll; background-repeat: repeat; background-color: rgb(205, 220, 238); border-image: initial;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: medium;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial; font-size: 12px;">Phương thức thanh toán</strong></span></td>
						<td align="center" style="margin: 8px; padding: 5px; color: rgb(0, 0, 0); font-weight: bold; cursor: text; background-image: none; background-attachment: scroll; background-repeat: repeat; background-color: rgb(205, 220, 238); border-image: initial;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: medium;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial; font-size: 12px;">Hướng dẫn sử dụng</strong></span></td>
					</tr>
					<tr>
						<td align="center" style="padding: 5px; border: 1px solid rgb(223, 235, 247) !important;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: medium;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial; font-size: 12px;">Tiền mặt trực tiếp</strong></span></td>
						<td align="left" style="padding: 5px; border: 1px solid rgb(223, 235, 247) !important;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">Quý khách có thể thanh toán tiền mặt khi nhân viên đến giao hàng tận nơi; hoặc đến Storm Store thanh toán tiền trước khi nhận hàng</span></td>
					</tr>
					<tr>
						<td align="center" style="padding: 5px; border: 1px solid rgb(223, 235, 247) !important;">
							<span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: medium;">
								<strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial; font-size: 12px;">
									<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">Thanh toán trực tuyến</strong></p>
									<strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">(Thẻ ATM only)</strong>
								</strong>
							</span>
						</td>
						<td align="left" style="padding: 5px; border: 1px solid rgb(223, 235, 247) !important;">
							<span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">
								<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial; font-size: 12px;">Thẻ của Quý khách phải được kích hoạt chức năng thanh toán trực tuyến hoặc đã đăng ký Internet Banking</p>
								Quý khách điền thông tin Thẻ theo các bước khi lựa chọn hình thức thanh toán trực tuyến trên webiste
							</span>
						</td>
					</tr>
					<tr>
						<td align="center" style="padding: 5px; border: 1px solid rgb(223, 235, 247) !important;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: medium;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial; font-size: 12px;">Chuyển khoản</strong></span></td>
						<td align="left" style="padding: 5px; border: 1px solid rgb(223, 235, 247) !important;">
							<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">Thông tin tài khoản:</strong></span></p>
							<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">Tên: Công ty Lầu 7 trường ĐH VL khoa CNTT</span></p>
							<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">Số tài khoản: 1 1 3&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">&nbsp;</strong></span></p>
							<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">Mở tại: Ngân hàng VL – 45 Nguyễn Khắc Nhu, Quận 1</span></p>
							<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">Nội dung:&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">Mua Online&nbsp;</strong><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">&nbsp;</strong></span></p>
							<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-family: Tahoma, Arial;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;"><em style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; text-decoration-line: underline;">Ghi chú:</span></em></strong><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;"><em style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">&nbsp;</em></strong><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;"><em style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">sau khi chuyển khoản, quý khách vui lòng </em></strong><em style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">thông báo cho chúng tôi việc chuyển tiền và số tài khoản của quý khách (bằng điện thoại, email, fax, …) để thuận tiện trong việc kiểm tra.</em></span></p>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;">&nbsp;</p>
		<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: medium;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; font-size: 12px;">II/ PHƯƠNG THỨC GIAO HÀNG</strong></span></p>
		<ol style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"></ol>
		<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">1. Sau khi bạn đặt hàng, trong vòng 24 giờ chúng tôi sẽ liên lạc lại để kiểm tra thông tin.</span></p>
		
		<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px; text-align: justify;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">2. Trong trường hợp giao hàng chậm trễ mà không báo trước, quý khách có thể từ chối nhận hàng và chúng tôi sẽ hoàn trả toàn bộ số tiền mà quý khách trả trước (nếu có) trong vòng 7 ngày.</span></p>
		<p style="margin-bottom: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Tahoma, Arial; font-size: 12px; text-align: justify;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-size: small;">3. Công ty&nbsp;cam kết tất cả hàng hóa gởi đến quý khách đều là hàng chính hãng mới 100% (có đầy đủ hóa đơn, được bảo hành chính thức). Những rủi ro phát sinh trong quá trình vận chuyển (va đập, ẩm ướt, tai nạn..) có thể ảnh hưởng đến hàng hóa, vì thế xin Quý Khách vui lòng kiểm tra hàng hóa thật kỹ trước khi ký nhận. Storm Store sẽ không chịu trách nhiệm với những sai lệch hình thức của hàng hoá sau khi Quý khách đã ký nhận hàng.</span></p>
	</section>
</div>
<?php require_once __DIR__. "/layout/footer.php"; ?>    